///=========================
#ifndef __APP_663X_INIT_H
#define __APP_663X_INIT_H

#define TEF663x_SlaveAddr    0xC6




#define HERO_STEP_INITTING     0
#define HERO_STEP_INIT_OK      1

#define PERIOHERALID_RDAC       0x32
#define PERIOHERALID_FDAC       0x33
#define DAC_ON 0x00
#define DAC_OFF 0x01



#define Hero_WriteData     I2C0_Tx
#define Hero_ReadData      I2C0_Rx



typedef enum
{
	HERO_INIT_STEP_COLDBOOT=0,
	HERO_INIT_STEP_RESET, 
	HERO_INIT_STEP_RADIO_IMPROVE_A,
	HERO_INIT_STEP_AUDIO_IMPROVE_A,
	HERO_INIT_STEP_KEYCODE1,
	HERO_INIT_STEP_USECASE,
	HERO_INIT_STEP_ACTIVE_DEVICE,
	HERO_INIT_STEP_RADIO_IMPROVE_B,
	HERO_INIT_STEP_AUDIO_IMPROVE_B,
	HERO_INIT_STEP_DAC,
	HERO_INIT_STEP_AUDIO_POINTER,
	HERO_INIT_STEP_PERIPHERAL,
	HERO_INIT_STEP_GPIO,
	HERO_INIT_STEP_SOURCE,
	HERO_INIT_STEP_AUDIO,
	HERO_INIT_STEP_RADIO,
	HERO_INIT_STEP_AudioImproveC,
	HERO_INIT_STEP_LIMITER,
	HERO_INIT_STEP_TUNER,
	HERO_INIT_STEP_CLICKCLACK,
	HERO_INIT_STEP_POLYCHIME,
	HERO_INIT_STEP_DELAY,
	HERO_INIT_STEP_SCALING,
	HERO_INIT_STEP_CHANNELGAIN,
	HERO_INIT_STEP_SOFTMUTE,
	HERO_INIT_STEP_LOUDNESS,
	HERO_INIT_STEP_VOLUME,
	HERO_INIT_STEP_GEQ,
	HERO_INIT_STEP_PEQ,
	HERO_INIT_STEP_DCFilter,
	HERO_INIT_STEP_NavPhoneFilter,
	HERO_INIT_STEP_FASTMUTE,
	HERO_INIT_STEP_CompExp,
	HERO_INIT_STEP_LimiterClipDet,
	HERO_INIT_STEP_Beep,
	HERO_INIT_STEP_RadioConfig,
	HERO_INIT_STEP_GSA,
	HERO_INIT_STEP_ADC,
	HERO_INIT_STEP_END
} Hero_Init_State;




typedef struct 
{
	Hero_Init_State nHeroInitState;	
	SCH_BOOL F_HeroInitOk;
	SCH_U16 Hero_Init_Timer;
}Hero_663x_T;
extern Hero_663x_T Hero663x;







extern void TASK_663x_Hero_Init(void);


#endif
